---
title: "My Publications"
---

Sclafani, A., PhD. Castillo, A., Carata, I., Pines, R., Berglas E., Jospeh, S., Sarker, J., Nashed, M., Roland, M., Arzayus, S., Williams, N., Glendinning, J., Bodnar, & R. J. PhD. (2023). Conditioned preference and avoidance induced in mice by the rare sugars      isomaltulose and allulose. *Physiology & Behavior*, 267, 114221

Roland, M., Berglas, E., Pines, R., Carata, I., Castillo, A., Nashed M., Sclafani, A., PhD., & Bodnar, R. J. PhD. (2023). Differential patterns of opioid and dopamine D1 receptor antagonism on nutritive and non-nutritive sweetener intakes in C57BL/6: 129 hybrid mice relative to inbred C57BL/6 and 129 mice. *Pharmacology Biochemistry and Behavior*, 173514. 

Nashed, M., Castillo, A., Roland, M., Carata, I., Berglas, E., Pines, R., Riaz, S., Jean-Phillipe Morisset, B., Sclafani, A., PhD., & Bodnar, R.J. (2021). Differential fructose and glucose appetition in DBA/2, 129P3 and C57BL/6× 129P3 hybrid mice revealed by sugar versus non-nutritive sweetener tests. *Physiology & Behavior*, 241, 113590. 
